branch-defaults:
  default:
    environment: flaskdemo-dev
    group_suffix: null
global:
  application_name: flaskdemo
  branch: null
  default_ec2_keyname: id_rsa
  default_platform: Python 3.4
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
